export const projectsData = [
  {
    id: 1,
    path: "/one",
    title: "conect four",
    description: "classic connect four game",
    tecnologies: ["html", "css", "js"],
    gitHubLink: "https://github.com/Manuelhh/connect-four",
    img: "https://res.cloudinary.com/mangud/image/upload/v1655037011/manuel/connectFour_rqb0fo.png",
    appLink: "https://cocky-goodall-e34f0c.netlify.app",
  },
  {
    id: 2,
    path: "/two",
    title: "timer app",
    description: "interactive timer",
    tecnologies: ["html", "css", "js"],
    gitHubLink: "https://github.com/Manuelhh/timer-app",
    img: "https://res.cloudinary.com/mangud/image/upload/v1655037217/manuel/timerApp_kprfnv.png",
    appLink: "https://manuelhh.github.io/timer-app/",
  },
  {
    id: 3,
    path: "/three",
    title: "hangman",
    description: "classic hangman game",
    tecnologies: ["html", "css", "js"],
    gitHubLink: "https://github.com/Manuelhh/hangman",
    img: "https://res.cloudinary.com/mangud/image/upload/v1655040269/manuel/Screen_Shot_2022-06-12_at_9.24.13_AM_ox2wg8.png",
    appLink: "https://optimistic-northcutt-494969.netlify.app",
  },
  {
    id: 4,
    path: "/four",
    title: "movie fihght app",
    description: "compares two given movies",
    tecnologies: ["axios", "js", "css"],
    gitHubLink: "https://github.com/Manuelhh/movie-fight-app",
    img: "https://res.cloudinary.com/mangud/image/upload/v1655037769/manuel/movieFight_nrycmy.png",
    appLink: "https://superlative-bunny-0d9bb2.netlify.app",
  },
  {
    id: 5,
    path: "/five",
    title: "html & css website",
    description: "html & css based website",
    tecnologies: ["htlm", "css", "queries"],
    gitHubLink: "",
    img: "https://res.cloudinary.com/mangud/image/upload/v1655037938/manuel/website_efsv77.png",
    appLink: "https://competent-easley-7a403a.netlify.app",
  },
  {
    id: 6,
    path: "/six",
    title: "applants",
    description: `the "instragram" to showcase your plants`,
    tecnologies: ["node js", "mongo", "express"],
    gitHubLink: "https://github.com/Manuelhh/applants",
    img: "https://res.cloudinary.com/mangud/image/upload/v1655038101/manuel/applants_xbwao1.png",
    appLink: "https://applants.herokuapp.com",
  },

  {
    id: 7,
    path: "/seven",
    title: "dogs api",
    description: "public api",
    tecnologies: ["node js", "mongo", "json"],
    gitHubLink: "https://github.com/Manuelhh/API-dogs",
    img: "https://res.cloudinary.com/mangud/image/upload/v1655041118/manuel/api_jp41gw.webp",
    appLink: "https://github.com/Manuelhh/API-dogs",
  },
  {
    id: 8,
    path: "/eight",
    title: "yelpcamp",
    description: "a yelp-like app for campsites",
    tecnologies: ["node js", "express", "mongo"],
    gitHubLink: "https://github.com/Manuelhh/yelpcamp-app",
    img: "https://res.cloudinary.com/mangud/image/upload/v1655038544/manuel/yelpcamp_lispaw.png",
    appLink: "https://mh-yelpcamp.herokuapp.com",
  },
  {
    id: 9,
    path: "/nine",
    title: "artist/academic personal website",
    description: "first project as a freelancer",
    tecnologies: ["react", "js", "hooks"],
    gitHubLink: "https://github.com/Manuelhh/marisela-website",
    img: "https://res.cloudinary.com/mangud/image/upload/v1655149324/manuel/marisela_hj00nt.png",
    appLink: "https://github.com/Manuelhh/marisela-website",
  },
];
